workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        certificate: ios_distribution  # Replace with the Codemagic certificate reference
        provisioning_profile: ios_provisioning_profile  # Replace with the Codemagic provisioning profile reference
        distribution_type: app_store  # Required for App Store/TestFlight
        bundle_identifier: chicks.food.app  # Add bundle identifier here
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --release --export-options-plist=ios/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
    integrations:
      app_store_connect: chicks_update  # Must match integration name in Codemagic UI
