workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest

    # <-- Tell Codemagic which CI-stored signing assets to use:
    code_signing:
      certificate: ios_distribution         # your P12 reference name in the UI
      provisioning_profile: ios_provisioning # your .mobileprovision reference name

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --release         # no --no-codesign so CI will sign it

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

    integrations:
      app_store_connect: chicks_update
