workflows:
  ios-release:
    name: iOS Release
    integrations:
      app_store_connect: chicks_update
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        provisioning_profiles:
          - ios_provisioning_profile
        certificates:
          - ios_distribution
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

