workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        provisioning_profile:
          - ios_provisioning_profile
        certificate:
          - ios_distribution 
        distribution_type: app_store  
        bundle_identifier: chicks.food.app  
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --release --export-options-plist=ios/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
    integrations:
      app_store_connect: chicks_update  # Must match integration name in Codemagic UI
