workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: api_key
        api_key:
          key_id: 93F9B8J34K           # Example: ABC123XYZ
          issuer_id: c55f0f22-1927-4567-9208-539ac79d4568     # From App Store Connect
          private_key: |
            -----BEGIN PRIVATE KEY-----
            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgycFon9J2c4YzkU42
            +I/v+ggF9sRJZvSvsWYer/z4gtigCgYIKoZIzj0DAQehRANCAAQDTpCpwD1e8coV
            ioBrqBJSRzav2ipVwspUoKbhx96uo6BySmu9qNGUVexI2cWKct6z+0mk4Xv/KJTD
            Yzbwamjs
            -----END PRIVATE KEY-----
        submit_to_testflight: true
