workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest

      signing:
        ios:
          distribution_certificate: ios_distribution      # the reference name you gave your .p12
          provisioning_profile: ios_provisioning_profile   # the reference name you gave your .mobileprovision

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

    integrations:
      app_store_connect: chicks_update
