workflows:
  ios-release:
    name: iOS Release
    inputs:
      - name: distribution_type
        type: enum
        enum: [ad_hoc, app_store, development, enterprise]
        default: app_store
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_certificate: 
          id: ios_distribution  # Reference name for your .p12 certificate
          type: certificate_reference
        provisioning_profile: 
          id: ios_provisioning_profile  # Reference name for your .mobileprovision file
          type: profile_reference
        distribution_type: "{{ inputs.distribution_type }}"  # Fixed enum value and input reference
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --release --export-options-plist=ios/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true