
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;


/* class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
 
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default : 
      return android;
    }
  }

  

/*   static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiflt3Nr-jVGA0Mrhfxp6HmDoVSYlrGh8',
    appId: '1:701237630047:web:70d86707648613f29a77ea',
    messagingSenderId: '701237630047',
    projectId: 'foodappshawarma-8b8ba',
    storageBucket: 'foodappshawarma-8b8ba.appspot.com',
  ); */

} */
